



export const languages = {
    en: { name: 'English', flag: '🇺🇸' },
    ru: { name: 'Русский', flag: '🇷🇺' },
};

export const voiceLanguages: Record<string, string> = {
    'en-US': 'English (US)',
    'ru-RU': 'Русский (RU)',
    'de-DE': 'Deutsch',
    'fr-FR': 'Français',
    'es-ES': 'Español',
    'it-IT': 'Italiano',
    'ja-JP': '日本語',
    'ko-KR': '한국어',
    'zh-CN': '中文 (Mandarin, Simplified)',
};

export const getLocale = (lang: 'en' | 'ru'): string => {
    return lang === 'ru' ? 'ru-RU' : 'en-US';
}

const translations = {
    en: {
        // Common
        'common.more': 'More',
        'common.back': 'Back',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.close': 'Close',
        'common.new': 'New',
        'common.confirm': 'Confirm',
        'common.today': 'Today',
        'common.untitled': 'Untitled Note',
        'common.note': 'note',
        'common.event': 'event',
        'common.reminder': 'reminder',
        'common.app': 'app',
        'common.note.plural': 'notes',
        'common.event.plural': 'events',
        'common.reminder.plural': 'reminders',
        'common.app.plural': 'apps',
        'common.search': 'Search {{context}}...',
        'common.listening': 'Listening...',
        'common.askNexus': 'Ask Nexus anything...',
        'common.unsavedChanges': 'You have unsaved changes.',
        'common.moreItems': '+{{count}} more',
        'common.new_entity': 'New {{entity}}',
        'common.edit_entity': 'Edit {{entity}}',
        'common.skip': 'Skip',

        // Header
        'header.title': 'Nexus AI',
        'header.greeting': 'Hi, {{name}}',
        'header.toggleUI': 'Hide/Show UI',
        'header.hideUI': 'Hide UI',
        'header.closeAllApps': 'Close All Apps',
        
        // Main Nav
        'nav.dashboard': 'Dashboard',
        'nav.calendar': 'Calendar',
        'nav.apps': 'Apps',
        'nav.chat': 'Chat',
        'nav.profile': 'Profile',
        'nav.settings': 'Settings',

        // Auth Flow
        'auth.language.title': 'Choose your language',
        'auth.language.description': 'Select the language for the interface.',
        'auth.theme.title': 'Select a theme',
        'auth.theme.description': 'You can always change this later in settings.',
        'auth.getStarted': 'Get Started',
        'auth.login.title': 'Welcome Back',
        'auth.register.title': 'Create Your Account',
        'auth.login.action': 'Log In',
        'auth.register.action': 'Create Account',
        'auth.login.switch': "Don't have an account? Sign Up",
        'auth.register.switch': 'Already have an account? Log In',
        'auth.agree.prefix': 'I agree to the',
        'auth.agree.terms': 'Terms of Use',
        'auth.agree.and': 'and',
        'auth.agree.policy': 'Privacy Policy',
        'auth.verify.title': 'Check Your Email',
        'auth.verify.message': "We've sent a confirmation link to",
        'auth.verify.instruction': 'Please click the link to complete your registration.',
        'auth.password.show': 'Show password',
        'auth.password.hide': 'Hide password',
        'auth.password.strength.length': 'Minimum 12 characters',
        'auth.password.strength.case': 'Uppercase & lowercase letters',
        'auth.password.strength.special': 'Includes special characters (!@#...)',
        'auth.password.strength.englishOnly': 'Only English letters, numbers, symbols',
        'auth.password.strength.crackTime': 'Estimated time to crack:',
        'auth.password.strength.crack.instantly': 'instantly',
        'auth.password.strength.crack.seconds': 'seconds',
        'auth.password.strength.crack.minutes': 'minutes',
        'auth.password.strength.crack.hours': 'hours',
        'auth.password.strength.crack.days': 'days',
        'auth.password.strength.crack.months': 'months',
        'auth.password.strength.crack.years': 'years',
        'auth.password.strength.crack.thousandYears': 'thousand years',
        'auth.password.strength.crack.centuries': 'centuries',
        
        // Chat
        'chat.title': 'Nexus Chat',
        'chat.clear': 'Clear Chat',
        'chat.pin': 'Pin to Left',
        'chat.greeting': 'Hello {{name}}! I\'m Nexus, your smart assistant. How can I help you today?',
        'chat.cleared': 'Chat cleared. How can I help you start fresh?',
        'chat.error.generic': 'Sorry, I encountered an error. Please try again.',
        'chat.error.badResponse': 'I seem to have generated an invalid response format. Could you try rephrasing?',
        'chat.error.init': 'AI service is currently unavailable. Please try again later.',
        'chat.noteUpdate': '{{summary}}',
        'chat.commandSummary': '{{successful}} out of {{total}} commands executed in {{time}}ms',
        'chat.reminderNotification': 'REMINDER: {{title}}',
        'chat.timerFinished': 'Timer "{{label}}" has finished.',
        'chat.appLaunchError': 'Error: App with ID "{{appId}}" not found.',

        // Onboarding
        'onboarding.welcome.title': 'Welcome to Nexus AI',
        'onboarding.welcome.description': "Your intelligent personal assistant, designed to seamlessly integrate with your thoughts and tasks. Let's get you set up.",
        'onboarding.demo1.title': 'I Understand Your Words',
        'onboarding.demo1.description': 'Just tell me what you need, and I\'ll handle the rest, from creating notes to managing your schedule.',
        'onboarding.demo1.prompt': 'Create a note with my project ideas: integrate new AI features and redesign user dashboard.',
        'onboarding.demo2.title': 'Stay Organized Effortlessly',
        'onboarding.demo2.description': 'I can set reminders, create calendar events, and help you keep track of everything important.',
        'onboarding.demo2.prompt': 'Remind me to call John tomorrow at 2 PM.',
        'onboarding.demo_notes.title': 'Rich Notes & Backgrounds',
        'onboarding.demo_notes.description': 'Create beautiful notes with rich text formatting and custom backgrounds to set the mood.',
        'onboarding.demo_calendar.title': 'Intuitive Calendar',
        'onboarding.demo_calendar.description': 'Click a day to see its agenda, or click-and-drag across multiple days to quickly create a multi-day event.',
        'onboarding.demo_customize.title': 'Total Customization',
        'onboarding.demo_customize.description': 'Make Nexus yours. Change themes, accent colors, navigation layouts, and much more in the Settings menu.',
        'onboarding.permissions.title': 'One Last Thing...',
        'onboarding.permissions.notificationsDescription': 'To provide timely reminders, Nexus AI needs permission to send you browser notifications.',
        'onboarding.permissions.grant': 'Enable Notifications',
        'onboarding.permissions.granted': 'Permissions granted. Thank you!',
        'onboarding.permissions.denied': 'Notifications disabled. You can change this in your browser settings later.',
        'onboarding.finish.title': "You're all set!",
        'onboarding.finish.description': "You're ready to start organizing your life with Nexus AI.",
        'onboarding.finish.button': 'Finish',
        'onboarding.next': 'Next',
        'onboarding.back': 'Back',
        'onboarding.continue': 'Continue',
        'onboarding.welcomeMessage': 'Welcome, {{name}}! It\'s great to meet you. I\'ve saved your profile. How can I help you get started?',

        // Confirmation Modals
        'confirmation.title': 'Nexus needs more information',
        'deleteModal.title': 'Delete {{itemType}}',
        'deleteModal.message': 'Are you sure you want to delete "{{itemName}}"? This action cannot be undone.',
        'discardModal.title': 'Discard Changes?',
        'discardModal.message': 'You have unsaved changes. Are you sure you want to discard them and close the settings?',
        'discardModal.confirm': 'Discard',
        'langChange.title': 'Reload Required',
        'langChange.message': 'To apply the new language, the application must be reloaded. Any unsaved work may be lost. Continue?',
        'langChange.confirm': 'Reload',
        'deleteDataModal.title': 'Are you absolutely sure?',
        'deleteDataModal.message': 'This action is irreversible. It will permanently delete all local data associated with your account from this device.',
        'deleteDataModal.dataSummary': 'You currently have: {{notesCount}} notes, {{eventsCount}} events, and {{remindersCount}} reminders.',
        'deleteDataModal.confirmPhrase': 'Please type `delete my data` to confirm.',
        'deleteDataModal.confirm': 'Delete Everything',


        // Settings
        'settings.title': 'Settings',
        'settings.save': 'Save Changes',
        // Settings: Personalization
        'settings.personalization.title': 'Personalization',
        'settings.personalization.theme': 'Theme',
        'settings.personalization.theme.light': 'Light',
        'settings.personalization.theme.dark': 'Dark',
        'settings.personalization.contrast': 'Contrast',
        'settings.personalization.contrast.description': 'Adjust visual contrast. {{theme}} theme is selected.',
        'settings.personalization.contrast.low': 'low',
        'settings.personalization.contrast.medium': 'medium',
        'settings.personalization.contrast.high': 'high',
        'settings.personalization.accent': 'Accent Color',
        'settings.personalization.accent.custom': 'Choose custom color',
        'settings.personalization.calendarBg': 'Calendar Background',
        'settings.personalization.calendarBg.none': 'None',
        'settings.personalization.calendarBg.upload': 'Upload',
        'settings.personalization.calendarBg.dim': 'Dim Background:',
        'settings.personalization.calendarBg.preset.paper': 'Paper',
        'settings.personalization.calendarBg.preset.wood': 'Wood',
        'settings.personalization.noteBg.preset.cosmos': 'Cosmos',
        'settings.personalization.noteBg.preset.beach': 'Beach',
        'settings.personalization.noteBg.preset.forest': 'Forest',
        // Settings: Navigation
        'settings.navigation.title': 'Navigation',
        'settings.navigation.desktopStyle': 'Desktop Navigation Style',
        'settings.navigation.desktopStyle.description': 'Choose how to navigate on desktop devices.',
        'settings.navigation.desktopStyle.header': 'Header',
        'settings.navigation.desktopStyle.header.desc': 'Classic navigation bar at the top of the screen.',
        'settings.navigation.desktopStyle.sidebarLeft': 'Side Bar (Left)',
        'settings.navigation.desktopStyle.sidebarLeft.desc': 'A vertical navigation bar pinned to the left.',
        'settings.navigation.desktopStyle.sidebarRight': 'Side Bar (Right)',
        'settings.navigation.desktopStyle.sidebarRight.desc': 'A vertical navigation bar pinned to the right.',
        'settings.navigation.sidebarLabels': 'Side bar label display style.',
        'settings.navigation.sidebarLabels.show': 'Show Labels',
        'settings.navigation.sidebarLabels.show.desc': 'Always show icon labels.',
        'settings.navigation.sidebarLabels.hover': 'Show on Hover',
        'settings.navigation.sidebarLabels.hover.desc': 'Only show labels when you hover over the bar.',
        'settings.navigation.mobileStyle': 'Mobile Navigation Style',
        'settings.navigation.mobileStyle.description': 'Choose how to navigate on mobile devices. "Bottom Bar" is recommended for easier access.',
        'settings.navigation.mobileStyle.bottom': 'Bottom Bar',
        'settings.navigation.mobileStyle.bottom.desc': 'Modern navigation bar at the bottom for one-handed use.',
        'settings.navigation.mobileHeight': 'Adjust bottom bar height.',
        'settings.navigation.mobileHeight.normal': 'Normal',
        'settings.navigation.mobileHeight.normal.desc': 'Standard height with more spacing.',
        'settings.navigation.mobileHeight.compact': 'Compact',
        'settings.navigation.mobileHeight.compact.desc': 'Reduced height for more screen space.',
        'settings.navigation.customize': 'Customize Navigation Items',
        'settings.navigation.customize.header': 'Header & Side Bar Items',
        'settings.navigation.customize.header.desc': 'Items for Header (Desktop/Mobile) and Side Bar (Desktop) layouts. Drag to reorder or hide.',
        'settings.navigation.customize.bottomBar': 'Mobile Bottom Bar Items',
        'settings.navigation.customize.bottomBar.desc': 'Items for the mobile Bottom Bar layout. Up to 5 items are recommended.',
        'settings.navigation.customize.visible': 'Visible Items',
        'settings.navigation.customize.hidden': 'Hidden Items',
        'settings.navigation.customize.limitError': 'Too many items. Please move {{count}} to hidden.',
        // Settings: Language
        'settings.language.title': 'Language & Region',
        'settings.language.sectionTitle': 'Language & Region',
        'settings.language.appLanguage.title': 'Application Language',
        'settings.language.appLanguage.description': 'Change the display language of the app interface.',
        'settings.language.voiceInput.title': 'Voice Input Language',
        'settings.language.voiceInput.description': 'Select the language for speech-to-text recognition.',
        // Settings: Calendar
        'settings.calendar.title': 'Calendar Settings',
        'settings.calendar.general': 'General',
        'settings.calendar.startWeekOn': 'Start week on',
        'settings.calendar.startWeekOn.sunday': 'Sunday',
        'settings.calendar.startWeekOn.monday': 'Monday',
        'settings.calendar.showWeekNumbers': 'Show Week Numbers',
        'settings.calendar.showWeekNumbers.desc': 'Display the week number on the side of the month view.',
        'settings.calendar.showMonthNumber': 'Show Month Number',
        'settings.calendar.showMonthNumber.desc': 'Display month number (e.g., July (07)).',
        'settings.calendar.weekends': 'Weekends',
        'settings.calendar.highlightWeekends': 'Highlight Weekends',
        'settings.calendar.highlightWeekends.desc': 'Apply a subtle highlight to weekend days.',
        'settings.calendar.selectWeekends': 'Select which days are weekends:',
        // Settings: Interface
        'settings.interface.title': 'Interface Settings',
        'settings.interface.header': 'Header',
        'settings.interface.combineLogo': 'Combine Logo & UI Hide Button',
        'settings.interface.combineLogo.desc': 'Good for small screens. The logo will also hide/show the UI.',
        // Settings: Chat
        'settings.chat.title': 'AI Chat Settings',
        'settings.chat.interaction': 'Interaction Mode',
        'settings.chat.interaction.desc': 'Choose how you want to open the chat interface.',
        'settings.chat.interaction.overlay': 'Input Bar Overlay',
        'settings.chat.interaction.overlay.desc': 'A persistent input bar at the bottom. Focusing it opens the chat.',
        'settings.chat.interaction.header': 'Header Button',
        'settings.chat.interaction.header.desc': 'A dedicated button in the header to toggle the chat overlay.',
        // Settings: Account
        'settings.account.title': 'Account',
        'settings.account.deleteData': 'Delete All Local Data',
        'settings.account.deleteDataDesc': 'Permanently remove all notes, events, reminders and other data from this device. This cannot be undone.',
        'settings.account.restartOnboarding': 'Restart Onboarding',
        'settings.account.restartOnboardingDesc': 'See the introductory tour and welcome messages again.',
        
        // Profile Modal
        'profile.title': 'My Profile',
        'profile.firstName': 'First Name',
        'profile.lastName': 'Last Name',
        'profile.dob': 'Date of Birth',
        'profile.timezone': 'Timezone',
        'profile.about': 'About Me',
        'profile.memory.title': 'AI Memory',
        'profile.memory.description': 'This is for other facts and preferences I\'ve learned about you.',
        'profile.memory.empty': 'AI memory is empty.',
        'profile.memory.clearAll': 'Clear All AI Memory',

        // Apps Modal
        'apps.title': 'My Apps',
        'apps.editTitle': 'Edit App',
        'apps.createTitle': 'Create New App',
        'apps.createButton': 'Create New App',
        'apps.empty': 'No applications created yet. Ask me to make one, or create your own!',
        'apps.launch': 'Launch',
        'apps.appTitle': 'App Title',
        'apps.appTitle.placeholder': 'My Awesome App',
        'apps.html': 'HTML',
        'apps.css': 'CSS',
        'apps.js': 'JavaScript',
        
        // Side Panel / Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.notes': 'Notes',
        'dashboard.reminders': 'Reminders',
        'dashboard.events': 'Events',
        'dashboard.newNote': 'New Note',
        'dashboard.editNote': 'Edit Note',
        'dashboard.editFolder': 'Edit Folder',
        'dashboard.folderName': 'Folder Name',
        'dashboard.iconColor': 'Icon Color',
        'dashboard.chooseIcon': 'Choose an Icon',
        'dashboard.uploadIcon': 'Or Upload Your Own',
        'dashboard.chooseImage': 'Choose Image',
        'dashboard.saveChanges': 'Save Changes',
        'dashboard.noteCount': '{{count}} note',
        'dashboard.noteCount.plural': '{{count}} notes',
        'dashboard.updated': 'Updated: {{date}}',
        'dashboard.empty': 'No notes found. Ask me to create one!',
        'dashboard.overdue': 'Overdue',
        'dashboard.today': 'Today',
        'dashboard.upcoming': 'Upcoming',
        'dashboard.completed': 'Completed',
        'dashboard.reminders.empty': 'No reminders found.',
        'dashboard.events.empty': 'No events found.',
        'dashboard.newEvent': 'New Event',
        'dashboard.newReminder': 'New Reminder',
        'dashboard.daily.noItems': 'No events or reminders for this day.',
        'dashboard.note.attached': 'Attached Note:',
        'dashboard.note.empty': 'This note is empty. Click to edit.',
        'dashboard.note.folder_prefix': 'Folder',
        'dashboard.note.title.placeholder': 'Note Title...',
        'dashboard.note.folder.placeholder': 'Folder...',
        'dashboard.note.content.placeholder': 'Start writing your note...',
        'dashboard.note.style': 'Style',
        'dashboard.note.background': 'Background',
        'dashboard.note.dim': 'Dim',
        'dashboard.itemEditor.title.placeholder': '{{type}} Title',
        'dashboard.itemEditor.description.placeholder': 'Description...',
        'dashboard.itemEditor.allDay': 'All-day',
        'dashboard.itemEditor.start': 'Start',
        'dashboard.itemEditor.end': 'End',
        'dashboard.itemEditor.datetime': 'Date & Time',
        'dashboard.itemEditor.color': 'Color',
        'dashboard.itemEditor.attachNote': 'Attach a note (optional)',
        'dashboard.itemEditor.delete_entity': 'Delete {{type}}',
        'dashboard.itemEditor.error.title': 'Title cannot be empty.',
        'dashboard.itemEditor.error.dates.invalid': 'One or more dates are invalid.',
        'dashboard.itemEditor.error.dates.order': 'End time must be after start time.',
        'dashboard.itemEditor.error.dates.duration': 'Event duration must be at least 5 minutes.',
        'dashboard.itemEditor.sheet.prompt': 'Drag up to add more details',

        // Storage Banner
        'storage.full.title': 'Storage Full',
        'storage.full.message': 'Cannot save new data. Please clear some space. A good place to start is your chat history.',
        'storage.full.action': 'Clear Chat History',
    },
    ru: {
        // Common
        'common.more': 'Ещё',
        'common.back': 'Назад',
        'common.save': 'Сохранить',
        'common.cancel': 'Отмена',
        'common.delete': 'Удалить',
        'common.edit': 'Изменить',
        'common.close': 'Закрыть',
        'common.new': 'Новый',
        'common.confirm': 'Подтвердить',
        'common.today': 'Сегодня',
        'common.untitled': 'Новая заметка',
        'common.note': 'заметку',
        'common.event': 'событие',
        'common.reminder': 'напоминание',
        'common.app': 'приложение',
        'common.note.plural': 'заметки',
        'common.event.plural': 'события',
        'common.reminder.plural': 'напоминания',
        'common.app.plural': 'приложения',
        'common.search': 'Искать в {{context}}...',
        'common.listening': 'Слушаю...',
        'common.askNexus': 'Спросите Nexus о чём угодно...',
        'common.unsavedChanges': 'У вас есть несохраненные изменения.',
        'common.moreItems': '+{{count}} еще',
        'common.new_entity': 'Новое {{entity}}',
        'common.edit_entity': 'Редактировать {{entity}}',
        'common.skip': 'Пропустить',

        // Header
        'header.title': 'Nexus AI',
        'header.greeting': 'Привет, {{name}}',
        'header.toggleUI': 'Скрыть/Показать UI',
        'header.hideUI': 'Скрыть UI',
        'header.closeAllApps': 'Закрыть все приложения',

        // Main Nav
        'nav.dashboard': 'Панель',
        'nav.calendar': 'Календарь',
        'nav.apps': 'Приложения',
        'nav.chat': 'Чат',
        'nav.profile': 'Профиль',
        'nav.settings': 'Настройки',

        // Auth Flow
        'auth.language.title': 'Выберите ваш язык',
        'auth.language.description': 'Выберите язык для интерфейса.',
        'auth.theme.title': 'Выберите тему',
        'auth.theme.description': 'Вы всегда можете изменить это позже в настройках.',
        'auth.getStarted': 'Начать',
        'auth.login.title': 'С возвращением',
        'auth.register.title': 'Создайте аккаунт',
        'auth.login.action': 'Войти',
        'auth.register.action': 'Создать аккаунт',
        'auth.login.switch': 'Нет аккаунта? Зарегистрироваться',
        'auth.register.switch': 'Уже есть аккаунт? Войти',
        'auth.agree.prefix': 'Я согласен с',
        'auth.agree.terms': 'Условиями использования',
        'auth.agree.and': 'и',
        'auth.agree.policy': 'Политикой конфиденциальности',
        'auth.verify.title': 'Проверьте вашу почту',
        'auth.verify.message': 'Мы отправили ссылку для подтверждения на',
        'auth.verify.instruction': 'Пожалуйста, перейдите по ссылке, чтобы завершить регистрацию.',
        'auth.password.show': 'Показать пароль',
        'auth.password.hide': 'Скрыть пароль',
        'auth.password.strength.length': 'Минимум 12 символов',
        'auth.password.strength.case': 'Заглавные и строчные буквы',
        'auth.password.strength.special': 'Включая спецсимволы (!@#...)',
        'auth.password.strength.englishOnly': 'Только английские буквы, цифры, символы',
        'auth.password.strength.crackTime': 'Примерное время для взлома:',
        'auth.password.strength.crack.instantly': 'мгновенно',
        'auth.password.strength.crack.seconds': 'секунд',
        'auth.password.strength.crack.minutes': 'минут',
        'auth.password.strength.crack.hours': 'часов',
        'auth.password.strength.crack.days': 'дней',
        'auth.password.strength.crack.months': 'месяцев',
        'auth.password.strength.crack.years': 'лет',
        'auth.password.strength.crack.thousandYears': 'тысяч лет',
        'auth.password.strength.crack.centuries': 'столетия',

        // Chat
        'chat.title': 'Nexus Чат',
        'chat.clear': 'Очистить чат',
        'chat.pin': 'Закрепить слева',
        'chat.greeting': 'Привет, {{name}}! Я Nexus, ваш умный помощник. Чем могу помочь сегодня?',
        'chat.cleared': 'Чат очищен. Как я могу помочь вам начать заново?',
        'chat.error.generic': 'К сожалению, произошла ошибка. Пожалуйста, попробуйте еще раз.',
        'chat.error.badResponse': 'Кажется, я сгенерировал неверный формат ответа. Не могли бы вы перефразировать?',
        'chat.error.init': 'Сервис ИИ в данный момент недоступен. Пожалуйста, попробуйте позже.',
        'chat.noteUpdate': '{{summary}}',
        'chat.commandSummary': '{{successful}} из {{total}} команд выполнено за {{time}}мс',
        'chat.reminderNotification': 'НАПОМИНАНИЕ: {{title}}',
        'chat.timerFinished': 'Таймер "{{label}}" завершен.',
        'chat.appLaunchError': 'Ошибка: Приложение с ID "{{appId}}" не найдено.',

        // Onboarding
        'onboarding.welcome.title': 'Добро пожаловать в Nexus AI',
        'onboarding.welcome.description': 'Ваш интеллектуальный личный помощник, созданный для органичной интеграции с вашими мыслями и задачами. Давайте вас настроим.',
        'onboarding.demo1.title': 'Я понимаю ваши слова',
        'onboarding.demo1.description': 'Просто скажите мне, что вам нужно, и я сделаю остальное, от создания заметок до управления вашим расписанием.',
        'onboarding.demo1.prompt': 'Создай заметку с идеями для проекта: интегрировать новые ИИ-фичи и переделать дашборд.',
        'onboarding.demo2.title': 'Оставайтесь организованным без усилий',
        'onboarding.demo2.description': 'Я могу устанавливать напоминания, создавать события в календаре и помогать вам отслеживать все важное.',
        'onboarding.demo2.prompt': 'Напомни мне позвонить Джону завтра в 14:00.',
        'onboarding.demo_notes.title': 'Заметки с форматом и фонами',
        'onboarding.demo_notes.description': 'Создавайте красивые заметки с форматированием и фонами, чтобы задать настроение.',
        'onboarding.demo_calendar.title': 'Интуитивный календарь',
        'onboarding.demo_calendar.description': 'Нажмите на день, чтобы увидеть его расписание, или нажмите и перетащите на несколько дней, чтобы быстро создать многодневное событие.',
        'onboarding.demo_customize.title': 'Полная настройка',
        'onboarding.demo_customize.description': 'Сделайте Nexus своим. Меняйте темы, цвета, навигацию и многое другое в меню Настроек.',
        'onboarding.permissions.title': 'И последнее...',
        'onboarding.permissions.notificationsDescription': 'Для своевременных напоминаний Nexus AI требуется разрешение на отправку вам браузерных уведомлений.',
        'onboarding.permissions.grant': 'Включить уведомления',
        'onboarding.permissions.granted': 'Разрешения предоставлены. Спасибо!',
        'onboarding.permissions.denied': 'Уведомления отключены. Вы можете изменить это позже в настройках браузера.',
        'onboarding.finish.title': 'Всё готово!',
        'onboarding.finish.description': 'Вы готовы начать организовывать свою жизнь с Nexus AI.',
        'onboarding.finish.button': 'Завершить',
        'onboarding.next': 'Далее',
        'onboarding.back': 'Назад',
        'onboarding.continue': 'Продолжить',
        'onboarding.welcomeMessage': 'Добро пожаловать, {{name}}! Рад знакомству. Я сохранил ваш профиль. С чего начнем?',

        // Confirmation Modals
        'confirmation.title': 'Nexus требуется дополнительная информация',
        'deleteModal.title': 'Удалить {{itemType}}',
        'deleteModal.message': 'Вы уверены, что хотите удалить "{{itemName}}"? Это действие нельзя будет отменить.',
        'discardModal.title': 'Отменить изменения?',
        'discardModal.message': 'У вас есть несохраненные изменения. Вы уверены, что хотите отменить их и закрыть настройки?',
        'discardModal.confirm': 'Отменить',
        'langChange.title': 'Требуется перезагрузка',
        'langChange.message': 'Для применения нового языка приложение должно быть перезагружено. Все несохраненные данные в открытых редакторах могут быть потеряны. Продолжить?',
        'langChange.confirm': 'Перезагрузить',
        'deleteDataModal.title': 'Вы абсолютно уверены?',
        'deleteDataModal.message': 'Это действие необратимо. Оно навсегда удалит все локальные данные, связанные с вашей учетной записью, с этого устройства.',
        'deleteDataModal.dataSummary': 'У вас сейчас: {{notesCount}} заметок, {{eventsCount}} событий и {{remindersCount}} напоминаний.',
        'deleteDataModal.confirmPhrase': 'Пожалуйста, введите `delete my data`, чтобы подтвердить.',
        'deleteDataModal.confirm': 'Удалить всё',
        
        // Settings
        'settings.title': 'Настройки',
        'settings.save': 'Сохранить изменения',
        // Settings: Personalization
        'settings.personalization.title': 'Персонализация',
        'settings.personalization.theme': 'Тема',
        'settings.personalization.theme.light': 'Светлая',
        'settings.personalization.theme.dark': 'Тёмная',
        'settings.personalization.contrast': 'Контраст',
        'settings.personalization.contrast.description': 'Настройте визуальный контраст. Выбрана {{theme}} тема.',
        'settings.personalization.contrast.low': 'низкий',
        'settings.personalization.contrast.medium': 'средний',
        'settings.personalization.contrast.high': 'высокий',
        'settings.personalization.accent': 'Акцентный цвет',
        'settings.personalization.accent.custom': 'Выбрать свой цвет',
        'settings.personalization.calendarBg': 'Фон календаря',
        'settings.personalization.calendarBg.none': 'Нет',
        'settings.personalization.calendarBg.upload': 'Загрузить',
        'settings.personalization.calendarBg.dim': 'Затемнение фона:',
        'settings.personalization.calendarBg.preset.paper': 'Бумага',
        'settings.personalization.calendarBg.preset.wood': 'Дерево',
        'settings.personalization.noteBg.preset.cosmos': 'Космос',
        'settings.personalization.noteBg.preset.beach': 'Пляж',
        'settings.personalization.noteBg.preset.forest': 'Лес',
        // Settings: Navigation
        'settings.navigation.title': 'Навигация',
        'settings.navigation.desktopStyle': 'Стиль навигации на ПК',
        'settings.navigation.desktopStyle.description': 'Выберите, как перемещаться по приложению на настольных компьютерах.',
        'settings.navigation.desktopStyle.header': 'Шапка',
        'settings.navigation.desktopStyle.header.desc': 'Классическая панель навигации вверху экрана.',
        'settings.navigation.desktopStyle.sidebarLeft': 'Боковая панель (слева)',
        'settings.navigation.desktopStyle.sidebarLeft.desc': 'Вертикальная панель навигации, закрепленная слева.',
        'settings.navigation.desktopStyle.sidebarRight': 'Боковая панель (справа)',
        'settings.navigation.desktopStyle.sidebarRight.desc': 'Вертикальная панель навигации, закрепленная справа.',
        'settings.navigation.sidebarLabels': 'Отображение меток боковой панели.',
        'settings.navigation.sidebarLabels.show': 'Показывать',
        'settings.navigation.sidebarLabels.show.desc': 'Всегда показывать метки иконок.',
        'settings.navigation.sidebarLabels.hover': 'При наведении',
        'settings.navigation.sidebarLabels.hover.desc': 'Показывать метки только при наведении на панель.',
        'settings.navigation.mobileStyle': 'Стиль навигации на мобильных',
        'settings.navigation.mobileStyle.description': 'Выберите, как перемещаться на мобильных устройствах. "Нижняя панель" рекомендуется для удобства.',
        'settings.navigation.mobileStyle.bottom': 'Нижняя панель',
        'settings.navigation.mobileStyle.bottom.desc': 'Современная панель навигации внизу для использования одной рукой.',
        'settings.navigation.mobileHeight': 'Настройте высоту нижней панели.',
        'settings.navigation.mobileHeight.normal': 'Обычная',
        'settings.navigation.mobileHeight.normal.desc': 'Стандартная высота с большим пространством.',
        'settings.navigation.mobileHeight.compact': 'Компактная',
        'settings.navigation.mobileHeight.compact.desc': 'Уменьшенная высота для большего пространства на экране.',
        'settings.navigation.customize': 'Настроить элементы навигации',
        'settings.navigation.customize.header': 'Элементы шапки и боковой панели',
        'settings.navigation.customize.header.desc': 'Элементы для шапки (ПК/моб.) и боковой панели (ПК). Перетащите для сортировки или скрытия.',
        'settings.navigation.customize.bottomBar': 'Элементы нижней мобильной панели',
        'settings.navigation.customize.bottomBar.desc': 'Элементы для нижней мобильной панели. Рекомендуется до 5 элементов.',
        'settings.navigation.customize.visible': 'Видимые элементы',
        'settings.navigation.customize.hidden': 'Скрытые элементы',
        'settings.navigation.customize.limitError': 'Слишком много элементов. Пожалуйста, переместите {{count}} в скрытые.',
        // Settings: Language
        'settings.language.title': 'Язык и регион',
        'settings.language.sectionTitle': 'Язык и регион',
        'settings.language.appLanguage.title': 'Язык приложения',
        'settings.language.appLanguage.description': 'Измените язык интерфейса приложения.',
        'settings.language.voiceInput.title': 'Язык голосового ввода',
        'settings.language.voiceInput.description': 'Выберите язык для распознавания речи.',
        // Settings: Calendar
        'settings.calendar.title': 'Настройки календаря',
        'settings.calendar.general': 'Общие',
        'settings.calendar.startWeekOn': 'Начинать неделю с',
        'settings.calendar.startWeekOn.sunday': 'Воскресенья',
        'settings.calendar.startWeekOn.monday': 'Понедельника',
        'settings.calendar.showWeekNumbers': 'Показывать номера недель',
        'settings.calendar.showWeekNumbers.desc': 'Отображать номер недели сбоку в режиме месяца.',
        'settings.calendar.showMonthNumber': 'Показывать номер месяца',
        'settings.calendar.showMonthNumber.desc': 'Отображать номер месяца (напр., Июль (07)).',
        'settings.calendar.weekends': 'Выходные',
        'settings.calendar.highlightWeekends': 'Выделять выходные',
        'settings.calendar.highlightWeekends.desc': 'Применять лёгкое выделение к выходным дням.',
        'settings.calendar.selectWeekends': 'Выберите, какие дни являются выходными:',
        // Settings: Interface
        'settings.interface.title': 'Настройки интерфейса',
        'settings.interface.header': 'Шапка',
        'settings.interface.combineLogo': 'Объединить логотип и кнопку скрытия UI',
        'settings.interface.combineLogo.desc': 'Удобно для маленьких экранов. Логотип также будет скрывать/показывать UI.',
        // Settings: Chat
        'settings.chat.title': 'Настройки чата с ИИ',
        'settings.chat.interaction': 'Режим взаимодействия',
        'settings.chat.interaction.desc': 'Выберите, как вы хотите открывать интерфейс чата.',
        'settings.chat.interaction.overlay': 'Строка ввода с оверлеем',
        'settings.chat.interaction.overlay.desc': 'Постоянная строка ввода внизу. При клике открывается чат.',
        'settings.chat.interaction.header': 'Кнопка в шапке',
        'settings.chat.interaction.header.desc': 'Специальная кнопка в шапке для переключения оверлея чата.',
        // Settings: Account
        'settings.account.title': 'Аккаунт',
        'settings.account.deleteData': 'Удалить все локальные данные',
        'settings.account.deleteDataDesc': 'Безвозвратно удалить все заметки, события, напоминания и другие данные с этого устройства. Это действие нельзя отменить.',
        'settings.account.restartOnboarding': 'Перезапустить обучение',
        'settings.account.restartOnboardingDesc': 'Снова посмотреть вступительный тур и приветственные сообщения.',

        // Profile Modal
        'profile.title': 'Мой профиль',
        'profile.firstName': 'Имя',
        'profile.lastName': 'Фамилия',
        'profile.dob': 'Дата рождения',
        'profile.timezone': 'Часовой пояс',
        'profile.about': 'Обо мне',
        'profile.memory.title': 'Память ИИ',
        'profile.memory.description': 'Здесь хранятся другие факты и предпочтения, которые я узнал о вас.',
        'profile.memory.empty': 'Память ИИ пуста.',
        'profile.memory.clearAll': 'Очистить всю память ИИ',

        // Apps Modal
        'apps.title': 'Мои приложения',
        'apps.editTitle': 'Редактировать приложение',
        'apps.createTitle': 'Создать новое приложение',
        'apps.createButton': 'Создать новое приложение',
        'apps.empty': 'Приложений пока нет. Попросите меня создать одно или сделайте сами!',
        'apps.launch': 'Запустить',
        'apps.appTitle': 'Название приложения',
        'apps.appTitle.placeholder': 'Мое крутое приложение',
        'apps.html': 'HTML',
        'apps.css': 'CSS',
        'apps.js': 'JavaScript',

         // Side Panel / Dashboard
         'dashboard.title': 'Панель',
         'dashboard.notes': 'Заметки',
         'dashboard.reminders': 'Напоминания',
         'dashboard.events': 'События',
         'dashboard.newNote': 'Новая заметка',
         'dashboard.editNote': 'Редактировать заметку',
         'dashboard.editFolder': 'Редактировать папку',
         'dashboard.folderName': 'Название папки',
         'dashboard.iconColor': 'Цвет иконки',
         'dashboard.chooseIcon': 'Выберите иконку',
         'dashboard.uploadIcon': 'Или загрузите свою',
         'dashboard.chooseImage': 'Выбрать изображение',
         'dashboard.saveChanges': 'Сохранить изменения',
         'dashboard.noteCount': '{{count}} заметка',
         'dashboard.noteCount.plural': '{{count}} заметок',
         'dashboard.updated': 'Обновлено: {{date}}',
         'dashboard.empty': 'Заметок нет. Попросите меня создать одну!',
         'dashboard.overdue': 'Просроченные',
         'dashboard.today': 'Сегодня',
         'dashboard.upcoming': 'Предстоящие',
         'dashboard.completed': 'Завершенные',
         'dashboard.reminders.empty': 'Напоминаний нет.',
         'dashboard.events.empty': 'Событий нет.',
         'dashboard.newEvent': 'Новое событие',
         'dashboard.newReminder': 'Новое напоминание',
         'dashboard.daily.noItems': 'На этот день нет событий или напоминаний.',
         'dashboard.note.attached': 'Прикрепленная заметка:',
         'dashboard.note.empty': 'Эта заметка пуста. Нажмите, чтобы отредактировать.',
         'dashboard.note.folder_prefix': 'Папка',
         'dashboard.note.title.placeholder': 'Заголовок заметки...',
         'dashboard.note.folder.placeholder': 'Папка...',
         'dashboard.note.content.placeholder': 'Начните писать вашу заметку...',
         'dashboard.note.style': 'Стиль',
         'dashboard.note.background': 'Фон',
         'dashboard.note.dim': 'Затемнение',
         'dashboard.itemEditor.title.placeholder': 'Заголовок {{type}}',
         'dashboard.itemEditor.description.placeholder': 'Описание...',
         'dashboard.itemEditor.allDay': 'Весь день',
         'dashboard.itemEditor.start': 'Начало',
         'dashboard.itemEditor.end': 'Конец',
         'dashboard.itemEditor.datetime': 'Дата и время',
         'dashboard.itemEditor.color': 'Цвет',
         'dashboard.itemEditor.attachNote': 'Прикрепить заметку (необязательно)',
         'dashboard.itemEditor.delete_entity': 'Удалить {{type}}',
         'dashboard.itemEditor.error.title': 'Заголовок не может быть пустым.',
         'dashboard.itemEditor.error.dates.invalid': 'Одна или несколько дат недействительны.',
         'dashboard.itemEditor.error.dates.order': 'Время окончания должно быть после времени начала.',
         'dashboard.itemEditor.error.dates.duration': 'Продолжительность события должна быть не менее 5 минут.',
         'dashboard.itemEditor.sheet.prompt': 'Потяните вверх для добавления деталей',

        // Storage Banner
        'storage.full.title': 'Хранилище заполнено',
        'storage.full.message': 'Не удается сохранить новые данные. Пожалуйста, освободите место. Хорошее начало — очистить историю чата.',
        'storage.full.action': 'Очистить историю чата',
    }
};

let currentLanguage: 'en' | 'ru' = 'en';

export const setLanguage = (lang: 'en' | 'ru') => {
    currentLanguage = lang;
};

export const t = (key: keyof typeof translations.en, params?: { [key: string]: string | number | undefined }): string => {
    let str = translations[currentLanguage]?.[key] || translations.en[key] || key;
    if (params) {
        Object.keys(params).forEach(pKey => {
            const value = params[pKey];
            if (value !== undefined) {
                str = str.replace(`{{${pKey}}}`, String(value));
            }
        });
    }
    return str;
};